module.exports = {
  development: {
    WETH: {
      name: 'ETH Wrapper Token',
      symbol: 'WETH',
      url: '',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    ZRX: {
      name: '0x Protocol Token',
      symbol: 'ZRX',
      url: 'https://www.0xproject.com',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    REP: {
      name: 'Augur Reputation Token',
      symbol: 'REP',
      url: 'https://www.augur.net/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    DGD: {
      name: 'Digix DAO Token',
      symbol: 'DGD',
      url: 'https://www.dgx.io/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    GNT: {
      name: 'Golem Netwok Token',
      symbol: 'GNT',
      url: 'https://golem.network/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    MKR: {
      name: 'MakerDAO',
      symbol: 'MKR',
      url: 'https://makerdao.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    MLN: {
      name: 'Melon Token',
      symbol: 'MLN',
      url: 'https://melonport.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
  },
};
