import { TokenInfoByNetwork } from '../../util/types';

export const tokenInfo: TokenInfoByNetwork = {
  development: [
    {
      name: '0x Protocol Token',
      symbol: 'ZRX',
      url: 'https://www.0xproject.com',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      name: 'Augur Reputation Token',
      symbol: 'REP',
      url: 'https://www.augur.net/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      name: 'Digix DAO Token',
      symbol: 'DGD',
      url: 'https://www.dgx.io/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      name: 'Golem Network Token',
      symbol: 'GNT',
      url: 'https://golem.network/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      name: 'MakerDAO',
      symbol: 'MKR',
      url: 'https://makerdao.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      name: 'Melon Token',
      symbol: 'MLN',
      url: 'https://melonport.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
  ],
  live: [
    {
      address: '0xecf8f87f810ecf450940c9f60066b4a7a501d6a7',
      name: 'ETH Wrapper Token',
      symbol: 'WETH',
      url: '',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      address: '0x48c80f1f4d53d5951e5d5438b54cba84f29f32a5',
      name: 'Augur Reputation Token',
      symbol: 'REP',
      url: 'https://www.augur.net/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      address: '0xe0b7927c4af23765cb51314a0e0521a9645f0e2a',
      name: 'Digix DAO Token',
      symbol: 'DGD',
      url: 'https://www.dgx.io/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      address: '0xa74476443119a942de498590fe1f2454d7d4ac0d',
      name: 'Golem Network Token',
      symbol: 'GNT',
      url: 'https://golem.network/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      address: '0xc66ea802717bfb9833400264dd12c2bceaa34a6d',
      name: 'MakerDAO',
      symbol: 'MKR',
      url: 'https://makerdao.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
    {
      address: '0xbeb9ef514a379b997e0798fdcc901ee474b6d9a1',
      name: 'Melon Token',
      symbol: 'MLN',
      url: 'https://melonport.com/',
      decimals: 18,
      ipfsHash: '0x0',
      swarmHash: '0x0',
    },
  ],
};
